const wishes=[['K','Kindness · La bienveillance','Que la douceur que tu offres te revienne en attentions sincères. Il y a des façons d’être qui touchent sans faire de bruit… Que la tienne rencontre toute la délicatesse qu’elle mérite.'],['E','Éclat','Que cette année te donne mille raisons de sourire. Certains sourires ont ce petit pouvoir de rendre un instant plus beau… Je te souhaite des journées à la hauteur du tien.'],['N','Noblesse de cœur','Que tu sois toujours appréciée pour ce que tu es. Que le respect, la paix et la sincérité accompagnent les liens que tu construis.'],['D','Détermination','Que tes projets trouvent leur chemin. Que Dieu te donne le courage de commencer, la patience de persévérer et la joie de voir tes efforts porter leurs fruits.'],['R','Rayonnement','Il y a des présences qui laissent une lumière après leur passage. Que cette nouvelle année t’offre, à ton tour, des rencontres et des instants dont la douceur reste longtemps.'],['A','Authenticité','Que tu restes libre d’être toi-même, dans tes rêves comme dans tes petits silences. Les personnes qui comptent n’ont pas besoin d’en faire davantage pour occuper une place particulière.']];
const opened=new Set(),dialog=document.querySelector('#letter');let current=0;
document.querySelector('#envelopes').innerHTML=wishes.map((w,i)=>`<button class="envelope" data-wish="${i}" aria-label="Ouvrir le souhait ${w[0]} : ${w[1]}"><span class="initial">${w[0]}</span><span class="label">À ouvrir</span></button>`).join('');
const unlockTimes=[Date.parse('2026-10-08T00:00:00-04:00'),Date.parse('2026-10-08T12:00:00-04:00'),Date.parse('2026-10-08T19:00:00-04:00')];
const scheduleLabels=['8 octobre à minuit','8 octobre à 12 h','8 octobre à 19 h'];let selectedChapter=0;
function chapter(n){selectedChapter=n;const locked=Date.now()<unlockTimes[n];document.querySelectorAll('.chapter').forEach((x,i)=>x.hidden=locked||i!==n);document.querySelector('#waiting').hidden=!locked;document.querySelectorAll('[data-chapter]').forEach((x,i)=>{x.classList.toggle('active',i===n);x.setAttribute('aria-selected',i===n);x.setAttribute('aria-label',`${['À minuit','Dans la journée','Le soir'][i]} — ${Date.now()<unlockTimes[i]?'ouverture le '+scheduleLabels[i]:'disponible'}`)});if(locked){document.querySelector('#waiting-text').textContent=`Ce moment se dévoilera le ${scheduleLabels[n]}, heure d’Haïti. Une petite attente… pour une attention choisie.`;const left=Math.max(0,Math.ceil((unlockTimes[n]-Date.now())/1000));document.querySelector('#countdown').textContent=`Encore ${Math.floor(left/3600)} h ${Math.floor(left%3600/60)} min ${left%60} s`}}
chapter(0);setInterval(()=>chapter(selectedChapter),1000);

document.querySelectorAll('[data-chapter]').forEach(x=>x.onclick=()=>chapter(+x.dataset.chapter));document.querySelectorAll('[data-next]').forEach(x=>x.onclick=()=>{chapter(+x.dataset.next);document.querySelector('#chapters').scrollIntoView({behavior:'smooth'})});
document.querySelectorAll('[data-wish]').forEach(x=>x.onclick=()=>{current=+x.dataset.wish;const w=wishes[current];document.querySelector('#letter-number').textContent=`SOUHAIT ${current+1} / 6`;document.querySelector('#letter-initial').textContent=w[0];document.querySelector('#letter-title').textContent=w[1];document.querySelector('#letter-text').textContent=w[2];opened.add(current);x.classList.add('opened');x.querySelector('.label').textContent='Relire mon souhait';document.querySelector('#progress').textContent=`${opened.size} / 6 souhaits découverts`;dialog.showModal()});
document.querySelector('#close').onclick=document.querySelector('#keep').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}};
const audio=new Audio('assets/all-of-me.mp3');audio.loop=true;audio.volume=.35;let musicOn=false;const musicButton=document.querySelector('#music');musicButton.onclick=async()=>{if(musicOn){audio.pause();musicOn=false}else{try{await audio.play();musicOn=true}catch(e){document.querySelector('#music-help').textContent='La musique ne peut pas démarrer pour le moment. Réessaie avec le bouton en haut à droite.';return}}musicButton.textContent=musicOn?'♪ Mettre la musique en pause':'♪ Activer la musique';musicButton.setAttribute('aria-pressed',musicOn)};
